# Generated by Django 5.2.7 on 2025-11-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
