# Generated by Django 5.2.7 on 2025-11-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_password_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
